sudo: required
language: java
language: kotlin
jdk:
- oraclejdk8
script:
- ./gradlew displayCommitHash
- ./gradlew isCI
- ./gradlew buildPlugin
before_install:
- chmod a+x gradlew
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/