environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
#

build_script:
  - gradlew displayCommitHash
  - gradlew buildPlugin --info
  - gradlew verifyPlugin --info
#

artifacts:
  - path: 'build\distributions\*.zip'
    name: julia-intellij
#
